package com.jhovanny.musicplayback.data.local.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents the schema for the `playlists` table in the local Room database.
 *
 * Each instance of this class corresponds to a single row in the table, representing
 * one playlist.
 *
 * @property id The unique identifier for the playlist. It is auto-generated by Room.
 * @property name The user-defined name of the playlist (e.g., "Workout Mix").
 * @property isSpecial A flag to distinguish system-generated playlists (like "Favorites")
 *                     from user-created playlists. `true` if it's a special playlist,
 *                     `false` otherwise.
 */
@Entity(tableName = "playlists")
data class PlaylistEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val isSpecial: Boolean = false
)